### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by i286-1** [JadHajjar/RoadBuilder-CSII#31]
Are netlanes going to be supported/used just like normal lanes in the future? For example a fence netlane in between a car lane and a train track

**Comment by JadHajjar** [comment]
Broadly, the answer is yes

We'll see how things work out

**Comment by Gilk260** [comment]
Is there any documentation for coding mod ? Like I want to dev my first mod but I'm a bit confused of how / where did you find the documentation to interact with roads and other stuff ?

**Comment by schott12521** [comment]
@Gilk260 I'd suggest going through Colossal Order's docs, and then exploring the source code of mods that you think are cool:

https://cs2.paradoxwikis.com/Modding_Toolchain
